version: '3.4'

services:
  mktfy.api:
    image: ${DOCKER_REGISTRY-}mktfyapi
    build:
      context: .
      dockerfile: MKTFY.Api/Dockerfile
    ports:
        - "34000:80"
        - "34001:443"

    environment:
        - ConnectionStrings__DefaultConnection=Server=mktfy.db;Database=devdb; User Id=devdbuser; Password=devdbpassword

        - Auth0__Domain=https://dev-bcybq3la.us.auth0.com
        - Auth0__Audience=http://mktfy.com
        - Auth0__TokenRedirectUrl=http://localhost/redirect

    depends_on:
        - mktfy.db

  mktfy.db:
    restart: on-failure
    image: "postgis/postgis:13-3.1-alpine"
    container_name: "mktfy.db"
    environment: 
        - POSTGRES_USER=devdbuser
        - POSTGRES_DB=devdb
        - POSTGRES_PASSWORD=devdbpassword
    volumes:
        - mktfy-db:/var/lib/postgresql/data
    ports:
        - "34010:5432"

volumes:
  mktfy-db: