version: '3.4'

services:
  mktfy.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

      - Auth0__ClientId=GAkPdd0zKdlWxpbExWhNlVCet0yV0ACT
      - Auth0__ClientSecret=Bo63l-qO6bYLl3J-w9EjmeU3GM0KbrBJ2zvAyJsZ5GCeVZS38irzWsUKOj22nKiA